config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("pineapple.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pineapple/users/urls.py
from django.urls import path

from pineapple.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

pineapple/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Django Pineapple.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

pineapple/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

pineapple/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

pineapple/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

pineapple/dashboard/templates/admin_doc/base_docs.html
{% extends "admin/base_site.html" %}

{% block extrastyle %}

<style>
    .literal-block, .doctest-block {
        background: #272822;
        color: #f8f8f2;
    }
    .module {
        padding: 20px;
    }
    .card-header .card-title a {
        color: #ffffff !important;
    }
    .card-header .card-title a:hover {
        color: #f8f8f2 !important;
    }
</style>
{% endblock %}

{% block content %}
{% block alerts %}{% endblock %}
<div id="content-main" class=col-12>
  <div class="col-12">
    <div class="card card-primary">
      <div class="card-body pad table-responsive">
          {% block docs_content %}{% endblock %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

pineapple/dashboard/templates/admin_doc/bookmarklets.html
{% extends "admin_doc/base_docs.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-docroot' %}">{% trans 'Documentation' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Bookmarklets' %}</li>
</ol>
{% endblock %}

{% block title %}{% trans "Documentation bookmarklets" %}{% endblock %}

{% block alerts %}
<div class="alert alert-info alert-dismissible col-12">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <h5><i class="icon fas fa-info"></i> Info</h5>
  <p>
      {% blocktrans trimmed %}
        To install bookmarklets, drag the link to your bookmarks toolbar, or right-click
        the link and add it to your bookmarks. Now you can select the bookmarklet
        from any page in the site.
      {% endblocktrans %}
  </p>
</div>
{% endblock %}

{% block docs_content %}
  <div class="card-body pad table-responsive">
    <h4><a href="javascript:(function(){if(typeof XMLHttpRequest!='undefined'){x=new XMLHttpRequest()}else{return;}x.open('HEAD',location.href,false);x.send(null);try{view=x.getResponseHeader('x-view');}catch(e){alert('No view found for this page');return;}if(view=='undefined'){alert('No view found for this page');}document.location='{% url 'django-admindocs-views-index' %}'+view+'/';})()">{% trans "Documentation for this page" %}</a></h4>
    <p>{% trans "Jumps you from any page to the documentation for the view that generates that page." %}</p>
  </div>
{% endblock %}

pineapple/dashboard/templates/admin_doc/index.html
{% extends "admin_doc/base_docs.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Documentation' %}</li>
</ol>
{% endblock %}

{% block title %}{% trans 'Documentation' %}{% endblock %}
{% block content_title %}{% trans 'Documentation' %}{% endblock %}

{% block content %}

<div id="content-main" class=col-12>
  <div class="col-12">
    <div class="card card-primary">
      <div class="card-body pad table-responsive">
        <h5><a href="tags/">{% trans 'Tags' %}</a></h5>
        <p>{% trans 'List of all the template tags and their functions.' %}</p>

        <h5><a href="filters/">{% trans 'Filters' %}</a></h5>
        <p>{% trans 'Filters are actions which can be applied to variables in a template to alter the output.' %}</p>

        <h5><a href="models/">{% trans 'Models' %}</a></h5>
        <p>{% trans 'Models are descriptions of all the objects in the system and their associated fields. Each model has a list of fields which can be accessed as template variables' %}.</p>

        <h5><a href="views/">{% trans 'Views' %}</a></h5>
        <p>{% trans 'Each page on the public site is generated by a view. The view defines which template is used to generate the page and which objects are available to that template.' %}</p>

        <h5><a href="bookmarklets/">{% trans 'Bookmarklets' %}</a></h5>
        <p>{% trans 'Tools for your browser to quickly access admin functionality.' %}</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

pineapple/dashboard/templates/admin_doc/missing_docutils.html
{% extends "admin_doc/base_docs.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Documentation' %}</li>
</ol>
{% endblock %}

{% block title %}{% trans 'Please install docutils' %}{% endblock %}
{% block content_title %}{% trans 'Documentation' %}{% endblock %}

{% block docs_content %}
  <h3>{% blocktrans with "http://docutils.sf.net/" as link %}The admin documentation system requires Python's <a href="{{ link }}">docutils</a> library.{% endblocktrans %}</h3>

  <p>{% blocktrans with "http://docutils.sf.net/" as link %}Please ask your administrators to install <a href="{{ link }}">docutils</a>.{% endblocktrans %}</p>
{% endblock %}

pineapple/dashboard/templates/admin_doc/model_detail.html
{% extends "admin_doc/base_docs.html" %}
{% load i18n %}

{% block extrahead %}
{{ block.super }}
<style type="text/css">
.module table { width:100%; }
.module table p { padding: 0; margin: 0; }
</style>
{% endblock %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-docroot' %}">{% trans 'Documentation' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-models-index' %}">{% trans 'Models' %}</a></li>
    <li class="breadcrumb-item active">{{ name }}</li>
</ol>
{% endblock %}

{% block title %}{% blocktrans %}Model: {{ name }}{% endblocktrans %}{% endblock %}
{% block content_title %}{{ name }}{% endblock %}

{% block docs_content %}
    <div class="card card-info">
        <div class="card-header"><h4>{% blocktrans %}Description{% endblocktrans %}</h4></div>
        <div class="card-body">
            {{ summary }}
            {{ description }}
        </div>
    </div>

    <div class="card card-success">
        <div class="card-header"><h4>{% trans 'Fields' %}</h4></div>
        <div class="card-body">
            <table class="table table-hover text-nowrap">
                <thead>
                <tr>
                    <th>{% trans 'Field' %}</th>
                    <th>{% trans 'Type' %}</th>
                    <th>{% trans 'Description' %}</th>
                </tr>
                </thead>

                <tbody>
                {% for field in fields|dictsort:"name" %}
                <tr>
                    <td>{{ field.name }}</td>
                    <td>{{ field.data_type }}</td>
                    <td>{{ field.verbose }}{% if field.help_text %} - {{ field.help_text|safe }}{% endif %}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% if methods %}
    <div class="card card-warning">
        <div class="card-header"><h4>{% trans 'Methods with arguments' %}</h4></div>
        <div class="card-body">
            <table class="table table-hover text-nowrap">
                <thead>
                <tr>
                    <th>{% trans 'Method' %}</th>
                    <th>{% trans 'Arguments' %}</th>
                    <th>{% trans 'Description' %}</th>
                </tr>
                </thead>

                <tbody>
                {% for method in methods|dictsort:"name" %}
                <tr>
                    <td>{{ method.name }}</td>
                    <td>{{ method.arguments }}</td>
                    <td>{{ method.verbose }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}

    <p class="small"><a href="{% url 'django-admindocs-models-index' %}">&lsaquo; {% trans 'Back to Model documentation' %}</a></p>
{% endblock %}

pineapple/dashboard/templates/admin_doc/model_index.html
{% extends "admin_doc/base_docs.html" %}
{% load i18n %}

{% block coltype %}colSM{% endblock %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-docroot' %}">{% trans 'Documentation' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Models' %}</li>
</ol>
{% endblock %}

{% block title %}{% trans 'Models' %}{% endblock %}
{% block content_title %}{% trans 'Models' %}{% endblock %}

{% block docs_content %}

{% regroup models by app_config as grouped_models %}

<div class="row">
    <div class="col-4 col-sm-2">
        <div class="nav flex-column nav-tabs h-100" id="tabs-tab" role="tablist" aria-orientation="vertical">
            {% for group in grouped_models %}
                <a class="nav-link" id="tabs-{{ group.grouper.label }}-control" data-toggle="pill" href="#tabs-{{ group.grouper.label }}" role="tab" aria-controls="tabs-{{ group.grouper.label }}" aria-selected="true">
                    <h6>{{ group.grouper.verbose_name }}</h6>
                </a>
            {% endfor %}
        </div>
    </div>

    <div class="col-7 col-sm-9">
        <div class="tab-content" id="tabs-tabContent">
            {% for group in grouped_models %}
                <div class="tab-pane text-left fade{% if forloop.first %} show active{% endif %}" id="tabs-{{ group.grouper.label }}" role="tabpanel" aria-labelledby="tabs-{{ group.grouper.label }}-control">

                    <ul>
                        {% for model in group.list %}
                            <li>
                                <a href="{% url 'django-admindocs-models-detail' app_label=model.app_label model_name=model.model_name %}">
                                    {{ model.object_name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>

                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

pineapple/dashboard/templates/admin_doc/template_detail.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-docroot' %}">{% trans 'Documentation' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Templates' %} {{ name }}</li>
</ol>
{% endblock %}

{% block title %}{% blocktrans %}Template: {{ name }}{% endblocktrans %}{% endblock %}
{% block content_title %}{% blocktrans %}Template: <q>{{ name }}</q>{% endblocktrans %}{% endblock %}

{% block docs_content %}
    {# Translators: Search is not a verb here, it qualifies path (a search path) #}
    <h2>{% blocktrans %}Search path for template <q>{{ name }}</q>:{% endblocktrans %}</h2>
    <ol>
    {% for template in templates|dictsort:"order" %}
        <li><code>{{ template.file }}</code>{% if not template.exists %} <em>{% trans '(does not exist)' %}</em>{% endif %}</li>
    {% endfor %}
    </ol>

    <p class="small"><a href="{% url 'django-admindocs-docroot' %}">&lsaquo; {% trans 'Back to Documentation' %}</a></p>
{% endblock %}

pineapple/dashboard/templates/admin_doc/template_filter_index.html
{% extends "admin_doc/base_docs.html" %}
{% load i18n %}

{% block coltype %}colSM{% endblock %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-docroot' %}">{% trans 'Documentation' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Filters' %}</li>
</ol>
{% endblock %}

{% block title %}{% trans 'Template filters' %}{% endblock %}
{% block content_title %}{% trans 'Template filters' %}{% endblock %}

{% block docs_content %}

{% regroup filters|dictsort:"library" by library as filter_libraries %}

  <div class="row">
    <div class="col-4 col-sm-2">
      <div class="nav flex-column nav-tabs h-100" id="filter-tab" role="tablist" aria-orientation="vertical">
        {% for library in filter_libraries %}
          <a class="nav-link" id="tabs-{% firstof library.grouper built_in_filters %}-tab" data-toggle="pill" href="#tabs-{% firstof library.grouper built_in_filters %}" role="tab" aria-controls="tabs-{% firstof library.grouper built_in_filters %}" aria-selected="true"><h6>{% firstof library.grouper _("Built-in filters") %}</h6></a>
        {% endfor %}
      </div>
    </div>

    <div class="col-7 col-sm-9">
      <div class="tab-content">
        {% for library in filter_libraries %}
        <div class="tab-pane text-left fade{% if forloop.first %} show active{% endif %}" id="tabs-{% firstof library.grouper built_in_filters %}" role="tabpanel" aria-labelledby="tabs-{% firstof library.grouper built_in_filters %}-tab">
          {% for view in ns_views.list|dictsort:"url" %}
              {% ifchanged %}
              <h4><a href="{% url 'django-admindocs-views-detail' view=view.full_name %}">{{ view.url }}</a></h4>
              <p class="small quiet">{% blocktrans with view.full_name as full_name and view.url_name as url_name %}View function: <code>{{ full_name }}</code>. Name: <code>{{ url_name }}</code>.{% endblocktrans %}</p>
              <p>{{ view.title }}</p>
              <hr>
              {% endifchanged %}
          {% endfor %}

          {% if library.grouper %}<p class="small quiet">{% blocktrans with code="{"|add:"% load "|add:library.grouper|add:" %"|add:"}" %}To use these filters, put <code>{{ code }}</code> in your template before using the filter.{% endblocktrans %}</p><hr>{% endif %}

          {% for filter in library.list|dictsort:"name" %}
            <h4 id="{{ library.grouper|default:"built_in" }}-{{ filter.name }}">{{ filter.name }}</h4>
            {{ filter.title }}
            {{ filter.body }}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

pineapple/dashboard/templates/admin_doc/template_tag_index.html
{% extends "admin_doc/base_docs.html" %}
{% load i18n %}

{% block coltype %}colSM{% endblock %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-docroot' %}">{% trans 'Documentation' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Tags' %}</li>
</ol>
{% endblock %}

{% block title %}{% trans 'Template tags' %}{% endblock %}
{% block content_title %}{% trans 'Template tag documentation' %}{% endblock %}

{% block docs_content %}

{% regroup tags|dictsort:"library" by library as tag_libraries %}

  <div class="row">
    <div class="col-4 col-sm-2">
      <div class="nav flex-column nav-tabs h-100" id="tabs-tab" role="tablist" aria-orientation="vertical">
        {% for library in tag_libraries %}
        <a class="nav-link" id="tabs-{% firstof library.grouper built_in_tags %}-tab" data-toggle="pill" href="#tabs-{% firstof library.grouper built_in_tags %}" role="tab" aria-controls="tabs-{% firstof library.grouper built_in_tags %}" aria-selected="true"><h6>{% firstof library.grouper _("Built-in tags") %}</h6></a>
        {% endfor %}
      </div>
    </div>

    <div class="col-7 col-sm-9">
      <div class="tab-content" id="tabs-tabContent">
        {% for library in tag_libraries %}
        <div class="tab-pane text-left fade{% if forloop.first %} show active{% endif %}" id="tabs-{% firstof library.grouper built_in_tags %}" role="tabpanel" aria-labelledby="tabs-{% firstof library.grouper built_in_tags %}-tab">
          {% if library.grouper %}<p class="small quiet">{% blocktrans with code="{"|add:"% load "|add:library.grouper|add:" %"|add:"}" %}To use these tags, put <code>{{ code }}</code> in your template before using the tag.{% endblocktrans %}</p><hr>{% endif %}
          {% for tag in library.list|dictsort:"name" %}
            <h3 id="{{ library.grouper|default:"built_in" }}-{{ tag.name }}">{{ tag.name }}</h3>
            <h6 style="font-style: italic;">{{ tag.title|striptags }}</h6>
              {{ tag.body }}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

pineapple/dashboard/templates/admin_doc/view_detail.html
{% extends "admin_doc/base_docs.html" %}
{% load i18n dashboard %}
{% get_dashboard_ui_tweaks as dashboard_ui %}

{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-docroot' %}">{% trans 'Documentation' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'django-admindocs-views-index' %}">{% trans 'Views' %}</a></li>
    <li class="breadcrumb-item active">{{ name }}</li>
</ol>
{% endblock %}

{% block title %}{% blocktrans %}View: {{ name }}{% endblocktrans %}{% endblock %}
{% block content_title %}{{ name }}{% endblock %}

{% block docs_content %}
    <h3 class="subhead">{{ summary|striptags }}</h3>

    {{ body }}

    {% if meta.Context %}
        <h4>{% trans 'Context:' %}</h4>
        <p>{{ meta.Context }}</p>
    {% endif %}

    {% if meta.Templates %}
        <h4>{% trans 'Templates:' %}</h4>
        <p>{{ meta.Templates }}</p>
    {% endif %}

    <div class="row">
        <div class="col-lg-3 col-sm-1"></div>
        <div class="col-lg-6 col-sm-10">
            <a class="btn btn-block {{ dashboard_ui.button_classes.info }}" href="{% url 'django-admindocs-views-index' %}">{% trans 'Back to View documentation' %}</a>
        </div>
        <div class="col-lg-3 col-sm-1"></div>
    </div>
{% endblock %}

pineapple/dashboard/templates/dashboard/includes/carousel.html
{% load i18n dashboard %}
{% get_dashboard_ui_tweaks as dashboard_ui %}

{% trans "General" as general_tab %}
{% get_sections adminform inline_admin_formsets as forms %}

<div id="jazzy-carousel" class="carousel slide" data-ride="false" data-wrap="false" data-keyboard="true" data-interval="false">
    <div class="row">
        <div class="col-sm-2">
            <a href="#jazzy-carousel" role="button" data-slide="prev" class="btn {{ dashboard_ui.button_classes.primary }}"><i class="fas fa-arrow-left"></i></a>
        </div>
        <div class="col-sm-8 text-center">
            <p class="carousel-fieldset-label">
                {{ forms.0.name|default:general_tab }}
            </p>
        </div>
        <div class="col-sm-2">
            <a href="#jazzy-carousel" role="button" data-slide="next" class="btn {{ dashboard_ui.button_classes.primary }} float-right"><i class="fas fa-arrow-right"></i></a>
        </div>
    </div>
    <ol class="carousel-indicators">
        {% for fieldset in forms %}
            <li data-target="#jazzy-carousel" data-slide-to="{{ forloop.counter0 }}"></li>
        {% endfor %}
    </ol>
    <div class="carousel-inner">
        {% for fieldset in forms %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}" data-carouselid="{{ forloop.counter0 }}" data-label="{{ fieldset.name|default:general_tab|capfirst }}" data-target="#{{ fieldset.name|default:general_tab|unicode_slugify }}-tab">
                {% if fieldset.is_inline %}
                    {% include fieldset.opts.template with inline_admin_formset=fieldset %}
                {% else %}
                    {% include "admin/includes/fieldset.html" with card=True %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>

pineapple/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

pineapple/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}